create extension if not exists "pgcrypto";

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'user_role'
  ) then
    create type public.user_role as enum ('admin', 'user');
  end if;
end $$;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  phone text,
  tiktok text,
  address_detail text,
  village text,
  province text,
  regency text,
  district text,
  postal_code text,
  email text not null unique,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  price bigint not null check (price >= 0),
  description text,
  image_url text,
  image_path text,
  stock integer not null default 0 check (stock >= 0),
  is_limited boolean not null default false,
  is_soldout boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  image_path text,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users(email);
create index if not exists idx_products_created_at on public.products(created_at desc);
create index if not exists idx_products_name on public.products(name);
create index if not exists idx_product_images_product_id on public.product_images(product_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    coalesce(new.email, ''),
    'user'
  )
  on conflict (id) do update
  set email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated, service_role;

alter table public.users enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;

drop policy if exists "Users can read own profile or admin" on public.users;
create policy "Users can read own profile or admin"
on public.users
for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "Users can insert own profile" on public.users;
create policy "Users can insert own profile"
on public.users
for insert
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Users can update own profile or admin" on public.users;
create policy "Users can update own profile or admin"
on public.users
for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "Admin can delete users" on public.users;
create policy "Admin can delete users"
on public.users
for delete
using (public.is_admin());

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Public can read product images" on public.product_images;
create policy "Public can read product images"
on public.product_images
for select
using (true);

drop policy if exists "Admins can insert product images" on public.product_images;
create policy "Admins can insert product images"
on public.product_images
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update product images" on public.product_images;
create policy "Admins can update product images"
on public.product_images
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete product images" on public.product_images;
create policy "Admins can delete product images"
on public.product_images
for delete
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/jpg']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view product-images bucket" on storage.objects;
create policy "Public can view product-images bucket"
on storage.objects
for select
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product-images bucket" on storage.objects;
create policy "Admins can upload product-images bucket"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can update product-images bucket" on storage.objects;
create policy "Admins can update product-images bucket"
on storage.objects
for update
to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "Admins can delete product-images bucket" on storage.objects;
create policy "Admins can delete product-images bucket"
on storage.objects
for delete
to authenticated
using (bucket_id = 'product-images' and public.is_admin());

-- Jalankan ini manual setelah user admin terdaftar:
-- update public.users set role = 'admin' where email = 'email-admin@contoh.com';
